### ISSUE TITLE
Example for AustrianPatient - Narrative contains empty "Urls" chapters

### ISSUE THREAD

**Issue by regelkraut** [HL7Austria/HL7-AT-FHIR-Core-R4#3]
**Real Submitter**
OÖG, Katharina Schuster

**Resource(s)/Profiles incl. Version**
Example for the Austrian Patient.

**Links**
https://hl7austria.github.io/r4-core-ballot_2021_01/Patient-AustrianPatientExample01.html

**Priority**
Minor

**Describe the bug**
Missing Urls: "Patient Religion" and "citizenship"

**To Reproduce**
see chapters 2.9.1.1 & 2.9.1.2

**Expected behavior**
Either remove the "Urls" part of the narrative or fill it with meaningful values.

**Attachments**
None

**Additional context**
This strange representation is created by the IG publisher.

**Comment by regelkraut** [comment]
**Ballot Info:** Ballot 2021-1

**Ballot Weight:** Z-K (approval with comment)

**Comment by oliver-krauss** [comment]
Has resolved itself. The URLs are not missing anymore but we now have "Pastafarianismus (unknown# 162)  We need to figure out if that unknown can be fixed

**Comment by Nik-xT** [comment]
To get instead of "unknown" a valid codesystem id, we should try to change the system value from the oid to the hl7 at core defining URLs.
Instead of `urn:oid:2.16.840.1.113883.2.16.1.4.1` we should write `http://hl7.at/fhir/HL7ATCoreProfiles/4.0.1/CodeSystem/at-core-cs-religion` and
instead of `urn:oid:1.0.3166.1.2.3` we should write `http://hl7.at/fhir/HL7ATCoreProfiles/4.0.1/CodeSystem/at-core-cs-iso-3166-1-alpha-3`
